nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "feathers-pinia@*":
    dependencies:
      "@feathersjs/commons": "*"
      "@feathersjs/adapter-commons": "*"
  "@intlify/vite-plugin-vue-i18n@*":
    dependencies:
      "vite": "*"
